In [49]:
import pandas as pd
import numpy as np

In [50]:
data = pd.read_csv('/Users/thuyduc/GG Advanced Data Analytics/Course 5/Module 4/Hypothesis testing with Python/marketing_sales_data.csv')
data.head()

TV      Radio  Social Media Influencer       Sales
0     Low   1.218354      1.270444      Micro   90.054222
1  Medium  14.949791      0.274451      Macro  222.741668
2     Low  10.377258      0.061984       Mega  102.774790
3    High  26.469274      7.070945      Micro  328.239378
4    High  36.876302      7.618605       Mega  351.807328

In [51]:
df = data[['Radio', 'Social Media', 'Sales']]
df

Radio  Social Media       Sales
0     1.218354      1.270444   90.054222
1    14.949791      0.274451  222.741668
2    10.377258      0.061984  102.774790
3    26.469274      7.070945  328.239378
4    36.876302      7.618605  351.807328
..         ...           ...         ...
567  28.210738      4.373466  302.887998
568  23.578661      2.856657  232.555023
569   9.169824      0.067279   73.888838
570  11.563403      1.727947  121.949570
571  18.814801      3.440682  182.511614

[572 rows x 3 columns]

In [52]:
w = np.array([2, 3])
x = np.array([1.218354, 1.270444])
b = 3

In [53]:
def linear_function(w, x, b):
    """Calculate y_hat using a linear function."""
    t = np.dot(w, x)
    y_hat = t + b
    return y_hat

y_hat = linear_function(w, x, b)
y_hat

9.24804

In [54]:
def loss_function(y, y_hat):
    """Calculate loss function."""
    loss = (y - y_hat)**2
    return loss


y = 90.054222
loss = loss_function(y, y_hat)
loss 

6529.639049417123

In [63]:
def gradient_descent(y, y_hat, x, w, b, alpha, dLdw, dLdb):
    """Find w, b using gradient descent"""
    
    w = w - alpha*dLdw
    b = b - alpha*dLdb
    #print(dLdw)
    return w, b

alpha = 0.01
dLdw = 3
dLdb = 4
w, b = gradient_descent(y, y_hat, x, w, b, alpha, dLdw, dLdb)
w, b

(array([3.9390107 , 5.02319458]), 4.57612364)

### SGD

In [68]:
# initialize w, b, epochs, alpha
w = np.array([2, 3])
b = 3
epochs = 5
alpha = 0.000000000001

for i in range(epochs):
    print(f'Epoch: {i+1}')
    for item in range(len(df)):
        # 1. Pick samples
        x = np.array([df['Radio'][item], df['Social Media'][item]])
        y = df['Sales'][item]
        
        # 2. Calculate y_hat
        y_hat = linear_function(w, x, b)

        # 3. Calculate loss
        loss = loss_function(y, y_hat)

        # 4. Calculate gradients/derivatives
        dLdw = 2*(y_hat - y)*x
        dLdb = 2*(y_hat - y)

        # 5. Update weights
        w, b = gradient_descent(y, y_hat, x, w, b, alpha, dLdw, dLdb)
        
        print(f'Iteration {item+1}: w = {w}, b = {b}, loss = {loss}')

Epoch: 1
Iteration 1: w = [2. 3.], b = 3.0000000001616125, loss = 6529.639218302045
Iteration 2: w = [2.00000001 3.        ], b = 3.00000000053965, loss = 35728.08163694323
Iteration 3: w = [2.00000001 3.        ], b = 3.0000000006973186, loss = 6214.850484405595
Iteration 4: w = [2.00000002 3.        ], b = 3.0000000011994947, loss = 63045.18117483493
Iteration 5: w = [2.00000004 3.00000001], b = 3.0000000017038926, loss = 63604.28942293977
Iteration 6: w = [2.00000005 3.00000001], b = 3.00000000208682, loss = 36658.40067145749
Iteration 7: w = [2.00000007 3.00000001], b = 3.0000000025901685, loss = 63339.96917035371
Iteration 8: w = [2.00000007 3.00000001], b = 3.000000002795652, loss = 10555.860095251264
Iteration 9: w = [2.00000008 3.00000001], b = 3.000000003186757, loss = 38240.74857434575
Iteration 10: w = [2.00000008 3.00000001], b = 3.000000003276202, loss = 2000.0945777370825
Iteration 11: w = [2.00000008 3.00000002], b = 3.0000000035106567, loss = 13742.270776174406
Iteratio

**Mini-batch**

In [61]:
np.array([df['Radio'][0:2], df['Social Media'][2-2:2]]).T[0]

array([1.21835388, 1.27044387])

In [80]:
#  initialize w, b, epochs, alpha
mini_batch = 4
w = np.array([5, 7])
b = 4
epochs = 5
alpha = 0.000000000001

for epoch in range(epochs):
    print(f'Epoch: {epoch+1}')

    for batch in np.arange(0, len(df), mini_batch):
        # 1. Pick samples (batch)
        x = np.array([df['Radio'][batch:batch+mini_batch], df['Social Media'][batch:batch+mini_batch]]).T
        y = df['Sales'][batch:batch+mini_batch].values

        cost = 0
        dLdw = 0
        dLdb = 0
        for i in range(mini_batch):
            # 2. Calculate y_hat
            y_hat_i = linear_function(w, x[i], b)

            # 3. Calculate loss
            cost += loss_function(y[i], y_hat_i)

            # 4. Calculate gradients/derivatives
            dLdw += 2*(y_hat_i - y[i])*x[i]
            dLdb += 2*(y_hat_i - y[i])
        
        loss = cost/mini_batch
        dLdb = dLdb/mini_batch
        dLdw = dLdw/mini_batch
        
        # 5. Update w, b
        w, b = gradient_descent(y, y_hat, x, w, b, alpha, dLdw, dLdb)
        
        
        print(f'Iteration {batch}: w = {w}, b = {b}, loss = {loss}')


Epoch: 1
Iteration 0: w = [5. 7.], b = 4.000000000200996, loss = 11917.485809975762
Iteration 4: w = [5.00000001 7.        ], b = 4.000000000383238, loss = 8895.606389848868
Iteration 8: w = [5.00000001 7.        ], b = 4.000000000524855, loss = 5681.98810702785
Iteration 12: w = [5.00000001 7.        ], b = 4.000000000656884, loss = 5028.592241760886
Iteration 16: w = [5.00000002 7.        ], b = 4.000000000842687, loss = 9203.867027767708
Iteration 20: w = [5.00000002 7.        ], b = 4.000000000998214, loss = 11557.67712683423
Iteration 24: w = [5.00000002 7.        ], b = 4.000000001081374, loss = 7831.496610800779
Iteration 28: w = [5.00000003 7.00000001], b = 4.000000001291042, loss = 13653.01335044279
Iteration 32: w = [5.00000003 7.00000001], b = 4.000000001428801, loss = 15078.15531500549
Iteration 36: w = [5.00000004 7.00000001], b = 4.000000001607272, loss = 9794.196960324578
Iteration 40: w = [5.00000004 7.00000001], b = 4.000000001743009, loss = 5889.860825574052
Iteration

In [56]:
np.arange(0, len(df), 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36