# Dataset

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [5]:
data = pd.read_csv('/Users/thuyduc/Python Learning/Applied Data Science Michigan/Resources/Course 1/Module 1/Datasets/Admission_Predict.csv')

data.columns = data.columns.str.strip()

data = data[['TOEFL Score','CGPA', 'Chance of Admit']].copy()
data = data.dropna()
data.head()


TOEFL Score  CGPA  Chance of Admit
0          118  9.65             0.92
1          107  8.87             0.76
2          104  8.00             0.72
3          110  8.67             0.80
4          103  8.21             0.65

# MSE

In [28]:
X = data[['TOEFL Score','CGPA']].to_numpy()
X = np.array([np.ones(X.shape[0]), X[:,0], X[:,1]]).T
y = data['Chance of Admit'].to_numpy()
w = np.random.rand(3)
X.shape, y.shape, w.shape

((400, 3), (400,), (3,))

In [ ]:
def calculate_y_hat(w, X):
    y_hat = np.dot(X, w)
    return y_hat

def calculate_loss_MSE(y, y_hat):
    loss = np.mean((y - y_hat)**2)
    return loss

def calculate_GD_MSE(w, X, y):
    y_hat = calculate_y_hat(w, X)
    dldw = -2 * np.mean((y - y_hat) * X.T, axis=1)
    return dldw

def calculate_GD(w, X, y, calculate_y_hat, calculate_loss):
    delta_w = 0.000001

    dldw = []
    y_hat = calculate_y_hat(w, X)
    loss = calculate_loss(y, y_hat)
    

    for i in range(len(w)):
        w_delta = w.copy()
        
        w_delta[i] = w_delta[i] + delta_w

        y_hat_delta = calculate_y_hat(w_delta, X)

        loss_delta = calculate_loss(y, y_hat_delta)

        loss_diff = (loss_delta - loss) / delta_w

        dldw.append(loss_diff)

    return np.array(dldw)

y_hat = calculate_y_hat(w, X)
loss = calculate_loss_MSE(y, y_hat)
gd = calculate_GD(w, X, y, calculate_y_hat, calculate_loss_MSE)
gd
calculate_GD_MSE(w, X, y), gd


(array([  202.42644492, 21810.85798694,  1746.33238562]),
 array([  202.42644678, 21810.86956261,  1746.33246206]))

# MAE

In [ ]:
X = data[['TOEFL Score','CGPA']].to_numpy()
X = np.array([np.ones(X.shape[0]), X[:,0], X[:,1]]).T
y = data['Chance of Admit'].to_numpy()
w = np.random.rand(3)
X.shape, y.shape, w.shape

In [36]:
def calculate_y_hat(w, X):
    y_hat = np.dot(X, w)
    return y_hat

def calculate_loss_MAE(y, y_hat):
    loss = np.mean(np.abs(y - y_hat))
    return loss

gd = calculate_GD(w, X, y, calculate_y_hat, calculate_loss_MAE)
gd

array([  1.00000003, 107.41      ,   8.59892499])

# Huber Loss

In [ ]:
X = data[['TOEFL Score','CGPA']].to_numpy()
X = np.array([np.ones(X.shape[0]), X[:,0], X[:,1]]).T
y = data['Chance of Admit'].to_numpy()
w = np.random.rand(3)
threshold = 0.001
X.shape, y.shape, w.shape

((400, 3), (400,), (3,))

In [ ]:
def calculate_y_hat(w, X):
    y_hat = np.dot(X, w)
    return y_hat

def calculate_huber_loss(y, y_hat, threshold):
    if np.abs(y - y_hat) <= threshold:
        cost = 0.5 * (y - y_hat)**2
        loss = np.mean(cost)
    else:
        cost = threshold * (np.abs(y - y_hat) - 0.5 * threshold)
        loss = np.mean(cost)
    
    return loss

def calculate_GD